CXX=g++
FLAGS= -std=c++0x -O3 -Wall #-DSTDOUT
LIBS= -lz

all: MemAddrStats.o

MemAddrStats.o: MemAddrStats.cpp epoch_engine.h epoch_engine.cc epoch_visitor.h epoch_visitor.cc mem_addr_parser.h mem_addr_parser.cc
	$(CXX) $(FLAGS) -o $@ $^ $(LIBS)
